TOP=$(HOME)
#CURRENT=$(PWD)
CURRENT=$(HOME)/Jesse/Src/echo
BASE_OMNI_TREE=$(HOME)
#VPATH=$(PWD)
VPATH=$(HOME)/Jesse/Src/echo
INSTALL=/usr/bin/install -c

include $(TOP)/mk/beforeauto.mk
include ./dir.mk
include $(TOP)/mk/afterauto.mk
