rm -rf .cache
rm -rf .config
rm -rf .dbus
rm -rf Desktop
#rm -rf Downloads
rm -rf .gconf
rm -rf .gnome2
rm -rf .gvfs
rm -rf .ICEauthority
rm -rf .local
rm -rf .mission-control
rm -rf .pki
rm -rf .presage
rm -rf .psensor
rm -rf .pulse
rm -rf .pulse-cookie
rm -rf .qt
rm -rf .vim
rm -rf .viminfo
rm -rf .w3m
rm -rf .wicd
rm -rf .xsession-errors
